#!/usr/bin/env python3

"""
Module to demonstrate an asynchronous comprehension that collects random float
values
from an asynchronous generator.
"""

import asyncio
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronously collects random float values from an asynchronous generator.

    The function uses an asynchronous comprehension to gather 10 random float
    values
    between 0 and 1 generated by the `async_generator` function.

    Returns:
        List[float]: A list of 10 random float values between 0 and 1.
    """
    return [i async for i in async_generator()]
